In [1]:
import numpy

In [2]:
import cv2

im_g = cv2.imread('smallgray.png', 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
type(im_g)

numpy.ndarray

In [4]:
im_g = cv2.imread('smallgray.png', 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [5]:
cv2.imwrite('newsmallgray.png', im_g)

True

In [6]:
ims = numpy.hstack((im_g, im_g)) #horizontal stacking - use tuple in argument since hstack takes only one argument
ims

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143],
        [187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147],
        [198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182],
        [209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [7]:
ims = numpy.vstack((im_g, im_g)) #vertical stacking - use tuple in argument since vstack takes only one argument
ims

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]],

       [[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [8]:
lst = numpy.vsplit(ims, 3)

In [9]:
lst

[array([[[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]],
 
        [[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]]], dtype=uint8),
 array([[[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]],
 
        [[187, 187, 187],
         [158, 158, 158],
         [104, 104, 104],
         [121, 121, 121],
         [143, 143, 143]]], dtype=uint8),
 array([[[198, 198, 198],
         [125, 125, 125],
         [255, 255, 255],
         [255, 255, 255],
         [147, 147, 147]],
 
        [[209, 209, 209],
         [134, 134, 134],
         [255, 255, 255],
         [ 97,  97,  97],
         [182, 182, 182]]], dtype=uint8)]

In [10]:
lst = numpy.hsplit(ims, 5)
lst

[array([[[187, 187, 187]],
 
        [[198, 198, 198]],
 
        [[209, 209, 209]],
 
        [[187, 187, 187]],
 
        [[198, 198, 198]],
 
        [[209, 209, 209]]], dtype=uint8),
 array([[[158, 158, 158]],
 
        [[125, 125, 125]],
 
        [[134, 134, 134]],
 
        [[158, 158, 158]],
 
        [[125, 125, 125]],
 
        [[134, 134, 134]]], dtype=uint8),
 array([[[104, 104, 104]],
 
        [[255, 255, 255]],
 
        [[255, 255, 255]],
 
        [[104, 104, 104]],
 
        [[255, 255, 255]],
 
        [[255, 255, 255]]], dtype=uint8),
 array([[[121, 121, 121]],
 
        [[255, 255, 255]],
 
        [[ 97,  97,  97]],
 
        [[121, 121, 121]],
 
        [[255, 255, 255]],
 
        [[ 97,  97,  97]]], dtype=uint8),
 array([[[143, 143, 143]],
 
        [[147, 147, 147]],
 
        [[182, 182, 182]],
 
        [[143, 143, 143]],
 
        [[147, 147, 147]],
 
        [[182, 182, 182]]], dtype=uint8)]